CREATE TABLE db_Hotel.user
(
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    user_name VARCHAR(100) DEFAULT "" NOT NULL,
    open_id VARCHAR(200) DEFAULT "" NOT NULL,
    head_img VARCHAR(300) DEFAULT "" NOT NULL,
    sex INT DEFAULT 0 NOT NULL,
    mobile VARCHAR(20) DEFAULT "" NOT NULL,
    email VARCHAR(50) DEFAULT "" NOT NULL,
    create_time BIGINT DEFAULT 0 NOT NULL,
    state INT DEFAULT 0 NOT NULL,
    star INT DEFAULT 0 NOT NULL
);


CREATE TABLE db_Hotel.hotel
(
  id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  hotel_name VARCHAR(100) DEFAULT "" NOT NULL COMMENT '名称',
  hotel_logo VARCHAR(300) DEFAULT "" NOT NULL COMMENT 'logo',
  hotel_img VARCHAR(2000) DEFAULT "" NOT NULL COMMENT '图片',
  address VARCHAR(200) DEFAULT "" NOT NULL COMMENT '地址',
  longitude DOUBLE DEFAULT 0.0 NOT NULL COMMENT '经度',
  latitude DOUBLE DEFAULT 0.0 NOT NULL COMMENT '纬度',
  phone VARCHAR(100) DEFAULT "" NOT NULL COMMENT '电话',
  state INT DEFAULT 0 NOT NULL COMMENT '1正常 0关闭',
  star INT DEFAULT 0 NOT NULL COMMENT '星级',
  open_time BIGINT DEFAULT 0 NOT NULL COMMENT '开店时间',
  create_time BIGINT DEFAULT 0 NOT NULL COMMENT '创建时间',
  mark DOUBLE DEFAULT 0.0 NOT NULL COMMENT '评分',
  comment_num int DEFAULT 0 NOT NULL COMMENT '评论数',
  description VARCHAR(3000) DEFAULT "" NOT NULL COMMENT '描述',
  account_id BIGINT DEFAULT 0 NOT NULL
);

CREATE TABLE db_Hotel.room
(
  id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  hotel_id BIGINT DEFAULT 0 NOT NULL,
  room_name VARCHAR(100) DEFAULT "" NOT NULL COMMENT '名称',
  room_logo VARCHAR(300) DEFAULT "" NOT NULL COMMENT 'logo',
  room_img VARCHAR(2000) DEFAULT "" NOT NULL COMMENT '图片',
  state INT DEFAULT 0 NOT NULL COMMENT '1正常 0关闭',
  stock INT DEFAULT 0 NOT NULL COMMENT '库存',
  create_time BIGINT DEFAULT 0 NOT NULL COMMENT '创建时间',
  description VARCHAR(3000) DEFAULT "" NOT NULL COMMENT '描述'
);
ALTER TABLE db_Hotel.room ADD INDEX(hotel_id);


CREATE TABLE db_Hotel.room_package
(
  id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  hotel_id BIGINT DEFAULT 0 NOT NULL,
  room_id BIGINT DEFAULT 0 NOT NULL,
  title VARCHAR(100) DEFAULT "" NOT NULL COMMENT '名称',
  img VARCHAR(2000) DEFAULT "" NOT NULL COMMENT '图片',
  state INT DEFAULT 0 NOT NULL COMMENT '1正常 0关闭',
  stock INT DEFAULT 0 NOT NULL COMMENT '库存',
  create_time BIGINT DEFAULT 0 NOT NULL COMMENT '创建时间',
  description VARCHAR(3000) DEFAULT "" NOT NULL COMMENT '描述'
);
ALTER TABLE db_Hotel.room_package ADD INDEX(hotel_id);
ALTER TABLE db_Hotel.room_package ADD INDEX(room_id);


CREATE TABLE db_Hotel.order
(
  id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  user_id BIGINT DEFAULT 0 NOT NULL,
  hotel_id BIGINT DEFAULT 0 NOT NULL,
  room_id BIGINT DEFAULT 0 NOT NULL,
  package_id BIGINT DEFAULT 0 NOT NULL,
  from_time BIGINT DEFAULT 0 NOT NULL,
  leave_time BIGINT DEFAULT 0 NOT NULL,
  come_time VARCHAR(50) DEFAULT "" NOT NULL COMMENT '到达时间',
  total_price DOUBLE DEFAULT 0.0 NOT NULL COMMENT '总价',
  remain_price DOUBLE DEFAULT 0.0 NOT NULL COMMENT '待付款',
  price_info VARCHAR(200) DEFAULT "" NOT NULL COMMENT '价格详情',
  user_name VARCHAR(50) DEFAULT "" NOT NULL,
  user_mobile VARCHAR(20) DEFAULT "" NOT NULL,
  user_identify_num VARCHAR(30) DEFAULT "" NOT NULL,
  invoice VARCHAR(200) DEFAULT "" NOT NULL COMMENT '发票',
  remark VARCHAR(500) DEFAULT "" NOT NULL COMMENT '备注',
  create_time BIGINT DEFAULT 0 NOT NULL COMMENT '创建时间'
);
ALTER TABLE db_Hotel.order ADD INDEX(user_id);
ALTER TABLE db_Hotel.order ADD INDEX(hotel_id);


#价格表
CREATE TABLE db_Hotel.room_price
(
  id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  hotel_id BIGINT DEFAULT 0 NOT NULL,
  room_id BIGINT DEFAULT 0 NOT NULL,
  package_id BIGINT DEFAULT 0 NOT NULL,
  price DOUBLE DEFAULT 0.0 NOT NULL,
  timestamp BIGINT DEFAULT 0 NOT NULL
);
ALTER TABLE db_Hotel.room_price ADD INDEX(hotel_id);
ALTER TABLE db_Hotel.room_price ADD INDEX(room_id);
ALTER TABLE db_Hotel.room_price ADD INDEX(package_id);

#账户
CREATE TABLE db_Hotel.account
(
  id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  email VARCHAR(100) DEFAULT "" NOT NULL,
  mobile VARCHAR(20) DEFAULT "" NOT NULL ,
  password VARCHAR(50) DEFAULT "" NOT NULL,
  u_type INT DEFAULT 1 NOT NULL ,
  create_time BIGINT DEFAULT 0 NOT NULL
);


